<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA5\x01\x0A\x0Bhello.proto\x12\x05hello\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"\x1C\x0A\x0DHelloResponse\x12\x0B\x0A\x03msg\x18\x01 \x01(\x092E\x0A\x0CHelloService\x125\x0A\x08SayHello\x12\x13.hello.HelloRequest\x1A\x14.hello.HelloResponseB\x04Z\x02./b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

